# Uncomment this line to define a global platform for your project
platform :ios, '15.5'  # ⬅️ Asegúrate de que esta versión sea compatible con tus dependencias

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Flutter Podfile setup
#require_relative '../flutter/bin/flutter'

flutter_root = File.expand_path('..', __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods flutter_root

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
